version: '3.3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nestjs-network
    restart: always
  main:
    container_name: notifier_app
    image: notifier-app:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017/notifier-app
    networks:
      - nestjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
  nestjs-network:
    driver: bridge
